# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  'dev:frontend':
    cmd: bun dev
    dir: ./frontend
  'dev:backend':
    cmd: air
    dir: ./backend
  dev:
    deps:
      - dev:frontend
      - dev:backend
  'test:frontend':
    cmd: bun run test
    dir: ./frontend
  'test:backend':
    cmd: go test ./...
    dir: ./backend
  test:
    deps:
      - test:frontend
      - test:backend
  'build:frontend':
    cmd: bun run build
    dir: ./frontend
  'build:backend':
    cmd: go build -o ./bin/server .
    dir: ./backend
  build:
    deps:
      - build:frontend
      - build:backend
